

#define PROTOLAYER_NAMESPACE protolayer
#define PROTOLAYER_NAMESPACE_BEGIN namespace PROTOLAYER_NAMESPACE {
#define PROTOLAYER_NAMESPACE_END }

#define XML_NAMESPACE xml
#define XML_PROTOLAYER_NAMESPACE_BEGIN PROTOLAYER_NAMESPACE_BEGIN { namespace XML_NAMESPACE {
#define XML_PROTOLAYER_NAMESPACE_END  }  }
#define XML_PROTOLAYER_NAMESPACE_QUALIFIER PROTOLAYER_NAMESPACE::XML_NAMESPACE 

